name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform-Actions"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
          
      - name: list files
        run: |
          echo "Listing files in $(pwd):"
          ls

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Format"
        run: terraform fmt
      
      - name: "Terraform Format Check"
        run: terraform fmt -check

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply --auto-approve

  s3-update:
    name: "Update S3 Bucket"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - shell: pwsh
      # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^WebAppResources/' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docs_changed"
          echo "docs_changed=$HasDiff" >> $GITHUB_OUTPUT

          echo "$diff"
          echo "$SourceDiff"
          echo "$docs_changed"
          echo "$HasDiff"

      - name: test echo
        # steps.<step_id>.outputs.<output name>
        run: |
          echo "test: ${{ steps.check_file_changed.outputs.docs_changed }}"

      - shell: pwsh
        # steps.<step_id>.outputs.<output name>
        run: |
          echo "test: ${{ steps.check_file_changed.outputs.docs_changed }}"


      - id: step1
        run: echo "name=hello" >> $GITHUB_OUTPUT

      - id: step2
        run: echo "name=test::world" >> $GITHUB_OUTPUT

      - name: Display
        run: |
          echo "Step 1 test: ${{ steps.step1.outputs.test }}"
          echo "Step 2 test: ${{ steps.step1.outputs.test }}"
        
          


    # Run the step only with "docs_changed" equals "True"
      - name: check if
        # steps.<step_id>.outputs.<output name>
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: echo "Updated"

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          ls

      - name: Update S3 Bucket
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          ls

  upload-key:
    name: "Upload EC2 Private Key"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        
      - name: Create temporary SSH key file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Upload EC2 Private Key
        uses: actions/upload-artifact@v3
        with:
          name: ec2-private-key
          path: ~/.ssh/id_rsa

  ec2-update:
    name: "Update EC2 Instance"
    runs-on: ubuntu-latest
    needs: [upload-key]

    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Download SSH Key
        uses: actions/download-artifact@v3
        with:
          name: ec2-private-key
          path: ~/.ssh/id_rsa

      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client

      - name: Update EC2 Files
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.before, '0000000000000000000000000000000000000000') || contains(github.event.commits.added, 'WebAppResources/WebServer/Server.py') || contains(github.event.commits.modified, 'WebAppResources/WebServer/Server.py')
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.AWS_EC2_PUBLIC_DNS }} "sudo rsync -avz WebAppResources/WebServer/Server.py ${{ secrets.AWS_EC2_SERVER_DIR }}"
          ssh -i ~/.ssh/id_rsa ${{ secrets.AWS_EC2_PUBLIC_DNS }} "sudo systemctl restart gunicorn"

