name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: "us-east-1"

jobs:
  terraform:
    name: "Terraform-Actions"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
          
      - name: list files
        run: |
          echo "Listing files in $(pwd):"
          ls

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Format"
        run: terraform fmt
      
      - name: "Terraform Format Check"
        run: terraform fmt -check

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply --auto-approve

  s3-update:
    name: "Update S3 Bucket"
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Update S3 Bucket
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.before, '0000000000000000000000000000000000000000') || contains(github.event.commits.added, 'WebAppResources/ReactApp/dist/') || contains(github.event.commits.modified, 'WebAppResources/ReactApp/dist/')
        run: |
          aws s3 sync WebAppResources/ReactApp/dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/

  upload-key:
    name: "Upload EC2 Private Key"
    runs-on: ubuntu-latest

    steps:
      - name: Create temporary SSH key file
        run: |
          
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ls ~/.ssh/
          chmod 600 ~/.ssh/id_rsa

      - name: Upload EC2 Private Key
        uses: actions/upload-artifact@v3
        with:
          name: ec2-private-key
          path: ~/.ssh/id_rsa

  ec2-update:
    name: "Update EC2 Instance"
    runs-on: ubuntu-latest
    needs: [upload-key]

    steps:
      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client

      - name: Download SSH Key
        uses: actions/download-artifact@v3
        with:
          name: ec2-private-key
          path: ~/.ssh/id_rsa

      - name: Update EC2 Files
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && contains(github.event.before, '0000000000000000000000000000000000000000') || contains(github.event.commits.added, 'WebAppResources/WebServer/Server.py') || contains(github.event.commits.modified, 'WebAppResources/WebServer/Server.py')
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.AWS_EC2_PUBLIC_DNS }} "sudo rsync -avz WebAppResources/WebServer/Server.py ${{ secrets.AWS_EC2_SERVER_DIR }}"
          ssh -i ~/.ssh/id_rsa ${{ secrets.AWS_EC2_PUBLIC_DNS }} "sudo systemctl restart gunicorn"

